//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.10

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "comp_team")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub team_id: String,
    pub player_id1: String,
    pub player_id2: String,
    pub name: String,
    pub rating: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
