//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.10

pub mod prelude;

pub mod comp_team;
pub mod duels_game;
pub mod duels_round;
pub mod fun_team;
pub mod guess;
pub mod location;
pub mod map;
pub mod player;
pub mod session;
pub mod solo_game;
pub mod solo_round;
pub mod user;
