//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.10

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "player")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub name: String,
    pub country_code: String,
    pub avatar_pin: String,
    pub level: i32,
    pub is_pro_user: bool,
    pub is_creator: bool,
    pub rating: Option<i32>,
    pub moving_rating: Option<i32>,
    pub no_move_rating: Option<i32>,
    pub nmpz_rating: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
