//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.10

pub use super::comp_team::Entity as CompTeam;
pub use super::duels_game::Entity as DuelsGame;
pub use super::duels_round::Entity as DuelsRound;
pub use super::fun_team::Entity as FunTeam;
pub use super::guess::Entity as Guess;
pub use super::location::Entity as Location;
pub use super::map::Entity as Map;
pub use super::player::Entity as Player;
pub use super::solo_game::Entity as SoloGame;
pub use super::solo_round::Entity as SoloRound;
